// Mocks generated by Mockito 5.4.0 from annotations
// in fm_rek/test/features/future_mind_mind_storage_mind/data/data_sources/remote/strange_mind_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fm_rek/core/data/future_mind_client/future_mind_client.dart'
    as _i2;
import 'package:fm_rek/features/future_mind_strange_mind/data/models/strange_mind_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FutureMindClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockFutureMindClient extends _i1.Mock implements _i2.FutureMindClient {
  MockFutureMindClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.StrangeMindModel>> getStrangeMindsList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getStrangeMindsList,
          [],
        ),
        returnValue: _i3.Future<List<_i4.StrangeMindModel>>.value(
            <_i4.StrangeMindModel>[]),
      ) as _i3.Future<List<_i4.StrangeMindModel>>);
}
